sudo: false

script: ./ci.sh

branches:
  only:
    - master

matrix:
  fast_finish: true
  include:
  - env: SUITE="js"
    language: node_js
  - env: SUITE="ruby"
    language: ruby
    rvm: 2.4.0
  - env: SUITE="ruby"
    language: ruby
    rvm: 2.3.3
  - env: SUITE="ruby"
    language: ruby
    rvm: 2.2.2
  - env: SUITE="rust"
    language: rust
    rust: stable
  - env: SUITE="rust"
    language: rust
    rust: nightly
